import {
  CategoryData,
  ServiceData,
  LocationData,
  AMCPackageData,
  PortfolioItemData,
  TestimonialData,
  BlogPostData,
  BusinessSettingsData,
} from "./types";

export const BUSINESS_SETTINGS: BusinessSettingsData = {
  companyName: "Al-Safwa Technical Services & Facility Management L.L.C.",
  phone: "+971 4 399 8877",
  emergencyHotline: "+971 50 882 1944",
  whatsappNumber: "971508821944",
  email: "support@alsafwa-technical.ae",
  address: "Level 24, Marina Plaza, Dubai Marina, PO Box 39200",
  city: "Dubai",
  country: "United Arab Emirates",
  openingHours: "Open 24 Hours / 7 Days a Week",
  dedLicense: "DED Commercial License #892147",
  dewaLicense: "DEWA Approved Contractor #EC-9941",
  municipalityLicense: "Dubai Municipality #DM-2023-4881",
  isoCertified: "ISO 9001:2015 Quality Management",
  bannerNotice: "24/7 Rapid Emergency Dispatch active across Dubai, Abu Dhabi & Sharjah. Average arrival in <25 mins.",
  bannerEnabled: true,
};

export const CATEGORIES: CategoryData[] = [
  {
    id: "cat-ac",
    name: "AC Services",
    slug: "ac-services",
    description: "Air conditioning repair, installation, seasonal maintenance, coil cleaning, and NADCA certified duct disinfection.",
    icon: "Fan",
    sortOrder: 1,
  },
  {
    id: "cat-plumbing",
    name: "Plumbing Services",
    slug: "plumbing",
    description: "Emergency leak detection, water pump overhaul, water heater replacement, drainage unblocking, and water tank cleaning.",
    icon: "Droplets",
    sortOrder: 2,
  },
  {
    id: "cat-electrical",
    name: "Electrical Services",
    slug: "electrical",
    description: "DEWA certified wiring, DB dressing, breaker tripping diagnostics, EV charger installation, and smart lighting.",
    icon: "Zap",
    sortOrder: 3,
  },
  {
    id: "cat-handyman",
    name: "Handyman & Carpentry",
    slug: "handyman",
    description: "Multi-skilled technicians for furniture assembly, TV wall mounting, door locks, curtain fixing, and woodwork.",
    icon: "Hammer",
    sortOrder: 4,
  },
  {
    id: "cat-painting",
    name: "Painting & Waterproofing",
    slug: "painting-waterproofing",
    description: "Interior Jotun luxury painting, UV-resistant exterior villa coatings, and foundation/roof waterproofing.",
    icon: "Paintbrush",
    sortOrder: 5,
  },
  {
    id: "cat-renovation",
    name: "Renovation & Fit-Out",
    slug: "renovation-fitout",
    description: "Turnkey kitchen, bathroom, and full villa renovations, marble crystallization, tiling, and false ceiling works.",
    icon: "Layers",
    sortOrder: 6,
  },
  {
    id: "cat-amc",
    name: "AMC & Property Maintenance",
    slug: "amc-packages",
    description: "365-day annual maintenance contracts for villas, apartments, offices, and commercial facilities with 24/7 priority SLA.",
    icon: "ShieldCheck",
    sortOrder: 7,
  },
  {
    id: "cat-cleaning",
    name: "Cleaning & Pool Maintenance",
    slug: "cleaning-maintenance",
    description: "Deep property sanitization, post-construction cleaning, and certified private villa swimming pool maintenance.",
    icon: "Sparkles",
    sortOrder: 8,
  },
];

export const SERVICES: ServiceData[] = [
  // AC Services
  {
    id: "srv-ac-repair",
    name: "Air Conditioning Repair",
    slug: "ac-repair",
    categoryId: "cat-ac",
    categorySlug: "ac-services",
    categoryName: "AC Services",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    shortDesc: "24/7 emergency AC repair, compressor diagnostics, capacitor replacement, gas charging (R410A / R22), and thermostat calibration.",
    fullContent: `Our DEWA-certified HVAC master technicians provide rapid-response diagnostic and troubleshooting services for all residential and commercial split, ducted, VRV, and package units. We carry genuine OEM replacement parts, specialized vacuum pumps, digital manifolds, and environmentally certified refrigerants to restore icy cooling within 60 minutes.`,
    basePriceAED: 180,
    priceUnit: "per inspection & diagnostic",
    emergencyAvailable: true,
    isPopular: true,
    isActive: true,
    features: [
      "Guaranteed 25–35 min rapid emergency response across Dubai & UAE",
      "Digital airflow and pressure leak detection testing",
      "OEM replacement capacitors, fan motors, and PCB controllers",
      "Eco-friendly R410A / R32 refrigerant recharge with leak seal warranty",
      "90-Day no-questions-asked warranty on all parts & workmanship",
    ],
    faqs: [
      {
        question: "Why is my AC blowing warm air in Dubai?",
        answer: "Warm air is typically caused by a failed start capacitor, low refrigerant due to micro-leaks, dirty condenser coils, or a faulty thermostat. Our technicians can diagnose and rectify this within 45 minutes on-site.",
      },
      {
        question: "How fast can an emergency HVAC technician arrive?",
        answer: "We maintain mobile response squads stationed in Dubai Marina, JVC, Palm Jumeirah, and Downtown, ensuring arrival in 20–35 minutes 24/7.",
      },
    ],
    metaTitle: "24/7 AC Repair Dubai & UAE | DEWA Certified Technicians",
    metaDesc: "Emergency AC repair in Dubai, Abu Dhabi & Sharjah. 25-minute response, OEM parts, 90-day warranty. Call +971 4 399 8877.",
  },
  {
    id: "srv-ac-installation",
    name: "AC Installation & Replacement",
    slug: "ac-installation",
    categoryId: "cat-ac",
    categorySlug: "ac-services",
    categoryName: "AC Services",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Professional installation of high-efficiency inverter split, ducted, and package AC units with certified copper piping.",
    fullContent: `Whether upgrading to high-efficiency energy-saving inverter units or replacing aging villa HVAC systems, our certified engineers calculate precise heat load (BTU/Ton) sizing and install O-General, Daikin, Carrier, Mitsubishi, and Gree systems with flawless vibration isolation and DEWA-compliant wiring.`,
    basePriceAED: 750,
    priceUnit: "per split unit installation",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Expert heat load BTU sizing and air distribution design",
      "Heavy-duty insulated copper tubing with nitrogen pressure testing",
      "Vibration isolator mounts and acoustic noise dampening",
      "Full manufacturer warranty plus 1-year workmanship guarantee",
      "Safe eco-friendly disposal of old equipment included",
    ],
    faqs: [
      {
        question: "Which AC brand is best suited for the UAE climate?",
        answer: "For desert heat and high humidity, we recommend O-General, Daikin, Carrier, or Mitsubishi Electric with tropical T3 compressors.",
      },
    ],
    metaTitle: "Professional AC Installation & Replacement Dubai UAE",
    metaDesc: "Certified split and ducted AC installation in Dubai. Authorized installer for O-General, Daikin, Carrier. Call for free site survey.",
  },
  {
    id: "srv-ac-maintenance",
    name: "AC Maintenance & Servicing",
    slug: "ac-maintenance",
    categoryId: "cat-ac",
    categorySlug: "ac-services",
    categoryName: "AC Services",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Preventative AC servicing, chemical coil pressure washing, filter disinfection, drainage line flushing, and electrical load checks.",
    fullContent: `Regular AC servicing prevents unexpected breakdowns and cuts DEWA electricity bills by up to 25%. Our 18-point comprehensive maintenance visit includes coil chemical washing, condensate drain chemical clearing, motor amp checks, and antibacterial misting.`,
    basePriceAED: 150,
    priceUnit: "per AC unit",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Chemical jet pressure cleaning of indoor and outdoor coils",
      "Condensate drain tray sanitization and clear flush",
      "Blower wheel deep cleaning and lubrication",
      "Thermostat sensor recalibration and amp draw check",
      "Antibacterial air filter sanitization spray",
    ],
    faqs: [
      {
        question: "How often should I service my AC in Dubai?",
        answer: "In the UAE, residential AC units should undergo routine preventative maintenance at least 3 to 4 times per year due to sand and humidity.",
      },
    ],
    metaTitle: "Comprehensive AC Maintenance & Servicing Dubai",
    metaDesc: "Top-rated AC maintenance in Dubai. 18-point precision check, coil chemical wash, gas check. Boost cooling & reduce DEWA bills.",
  },
  {
    id: "srv-ac-duct-cleaning",
    name: "AC Duct Cleaning & Sanitization",
    slug: "ac-duct-cleaning",
    categoryId: "cat-ac",
    categorySlug: "ac-services",
    categoryName: "AC Services",
    image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
    shortDesc: "NADCA-certified robotic brush duct cleaning, mold eradication, and Dubai Municipality approved organic fogging.",
    fullContent: `Eliminate trapped desert dust, black mold spores, and allergens from deep inside your HVAC ductwork. Using rotary brushing cameras and industrial HEPA negative air vacuums, we clean supply and return ducts, followed by organic hospital-grade sanitization.`,
    basePriceAED: 650,
    priceUnit: "per 2-Bedroom flat / zone",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Robotic camera live video inspection (Before & After footage)",
      "High-power HEPA 4-stage negative pressure air extraction",
      "Dubai Municipality approved 100% organic anti-microbial fogging",
      "Deep cleaning of diffusers, grilles, and blower chambers",
      "Improves indoor air quality and relieves asthma & dust allergies",
    ],
    faqs: [
      {
        question: "Is the disinfectant safe for children and pets?",
        answer: "Yes, we exclusively utilize organic, food-grade botanical disinfectants approved by Dubai Municipality.",
      },
    ],
    metaTitle: "NADCA Certified AC Duct Cleaning Dubai UAE",
    metaDesc: "Hospital-grade AC duct cleaning and mold sanitization in Dubai & UAE. Breath pure, allergen-free air.",
  },

  // Plumbing
  {
    id: "srv-plumbing",
    name: "Emergency Plumbing & Leak Detection",
    slug: "plumbing",
    categoryId: "cat-plumbing",
    categorySlug: "plumbing",
    categoryName: "Plumbing Services",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80",
    shortDesc: "24/7 rapid emergency plumbing, FLIR thermal leak detection, burst pipe repair, booster pump overhauls, and drain unblocking.",
    fullContent: `From sudden ceiling leaks and burst water pipes to silent underground line leaks causing skyrocketing DEWA bills, our licensed plumbers use non-destructive FLIR thermal imaging and acoustic sensors to find and fix leaks fast.`,
    basePriceAED: 199,
    priceUnit: "per emergency callout",
    emergencyAvailable: true,
    isPopular: true,
    isActive: true,
    features: [
      "Non-destructive FLIR thermal leak detection with zero wall breaking",
      "24/7 immediate response for burst PPR, PEX, and copper pipes",
      "Water booster pump repair, pressure vessel calibration, and switches",
      "High-pressure hydro-jetting for blocked main sewer drains",
      "90-Day warranty on all plumbing repairs and replacements",
    ],
    faqs: [
      {
        question: "How do you detect hidden leaks without breaking walls?",
        answer: "We deploy military-grade FLIR thermal imaging cameras and acoustic sensor rods that detect moisture differentials and pressurized pipe hiss through solid concrete and marble.",
      },
    ],
    metaTitle: "24/7 Emergency Plumber in Dubai | Thermal Leak Detection",
    metaDesc: "Immediate 24/7 plumber in Dubai. Thermal imaging leak detection, burst pipes, water pumps, blocked drains. 25-min response.",
  },
  {
    id: "srv-water-heater",
    name: "Water Heater Repair & Replacement",
    slug: "water-heater-repair",
    categoryId: "cat-plumbing",
    categorySlug: "plumbing",
    categoryName: "Plumbing Services",
    image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Same-day water heater replacement (Ariston, Atlantic, Milano), thermostat repair, pressure relief valve, and heating element fixes.",
    fullContent: `A malfunctioning water heater can cause complete loss of hot water or dangerous electrical leakage trips. We supply and install genuine Italian and European certified glass-lined storage and instant water heaters with full safety compliance.`,
    basePriceAED: 220,
    priceUnit: "per repair / replacement labour",
    emergencyAvailable: true,
    isPopular: false,
    isActive: true,
    features: [
      "Stocked with Ariston, Atlantic, and Milano water heaters",
      "Replacement of faulty heating elements, thermostats, and safety valves",
      "High-pressure dielectric union connections to stop galvanic corrosion",
      "Full DEWA grounding and circuit breaker load verification",
      "5-Year tank warranty and 1-year installation guarantee",
    ],
    faqs: [
      {
        question: "Why does my water heater trip the main electricity breaker?",
        answer: "This is usually caused by a ruptured heating element allowing water to contact the live electrical filament. Our plumber will isolate and replace the element safely.",
      },
    ],
    metaTitle: "Water Heater Repair & Installation Dubai | Ariston & Atlantic",
    metaDesc: "Same-day water heater replacement in Dubai. Italian glass-lined tanks, heating elements, safety valves. 24/7 emergency service.",
  },
  {
    id: "srv-water-tank-cleaning",
    name: "Water Tank Cleaning & Sanitization",
    slug: "water-tank-cleaning",
    categoryId: "cat-plumbing",
    categorySlug: "plumbing",
    categoryName: "Plumbing Services",
    image: "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Dubai Municipality approved GRP and concrete water tank deep cleaning, sludge extraction, and laboratory water test certification.",
    fullContent: `Rooftop and underground water tanks accumulate desert silt, rust, biofilm, and algae under extreme UAE heat. Our certified team drains, pressure-washes, vacuums sludge, and disinfects your domestic water storage, providing official municipality compliance certificates and lab test reports.`,
    basePriceAED: 450,
    priceUnit: "per villa tank",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Dubai Municipality and Abu Dhabi Food Authority compliant protocol",
      "Full sludge vacuuming and 250-bar high-pressure rotational washing",
      "Eco-friendly chlorine disinfection with neutralizer flushing",
      "Comprehensive 12-parameter post-treatment laboratory water analysis",
      "Official Water Tank Sanitization Compliance Certificate provided",
    ],
    faqs: [
      {
        question: "Is water tank cleaning mandatory in UAE villas?",
        answer: "Yes, Dubai Municipality guidelines recommend sanitizing domestic water storage tanks at least once every 6 months to prevent bacterial contamination.",
      },
    ],
    metaTitle: "Certified Water Tank Cleaning Dubai | Municipality Approved",
    metaDesc: "Professional water tank cleaning for villas and buildings in Dubai. Official lab test report & municipality certificate.",
  },

  // Electrical Services
  {
    id: "srv-electrical",
    name: "Electrical Repair & DEWA Services",
    slug: "electrical",
    categoryId: "cat-electrical",
    categorySlug: "electrical",
    categoryName: "Electrical Services",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    shortDesc: "DEWA approved electricians for short circuit troubleshooting, DB dressing, breaker tripping, rewiring, and surge protection.",
    fullContent: `From sudden circuit breaker trips leaving your residence in darkness to complete distribution board rewiring and power balancing, our licensed electricians ensure safety and compliance with DEWA regulations.`,
    basePriceAED: 180,
    priceUnit: "per diagnostic visit",
    emergencyAvailable: true,
    isPopular: true,
    isActive: true,
    features: [
      "DEWA & ADDC certified licensed master wiremen",
      "Distribution board (DB) load balancing and RCCB/ELCB tripping fixes",
      "Short circuit diagnosis using digital insulation megohmmeters",
      "Replacement of faulty switches, sockets, and heavy-duty contactors",
      "Emergency 24/7 power restoration response across UAE",
    ],
    faqs: [
      {
        question: "Why does my main circuit breaker keep tripping?",
        answer: "Main breaker trips are usually caused by ground-fault leakage in water heaters, outdoor garden lighting moisture ingress, or overloaded circuits. We locate the faulty line instantly.",
      },
    ],
    metaTitle: "24/7 Emergency Electrician Dubai | DEWA Approved Contractor",
    metaDesc: "Licensed electricians in Dubai. Short circuit repair, DB box dressing, breaker tripping, power restoration. 25-min response.",
  },
  {
    id: "srv-ev-charger",
    name: "EV Charger Installation (Tesla / Type 2)",
    slug: "ev-charger-installation",
    categoryId: "cat-electrical",
    categorySlug: "electrical",
    categoryName: "Electrical Services",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Turnkey residential 7kW / 11kW / 22kW EV wallbox charger installation with dedicated RCBO breakers and DEWA load compliance.",
    fullContent: `Charge your electric vehicle safely at home. We install Tesla Wall Connectors, Porsche, BMW, Mercedes, and universal Type 2 chargers with dedicated armoured cabling, RCBO safety breakers, and weatherproof isolators.`,
    basePriceAED: 950,
    priceUnit: "per standard residential installation",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Compatible with Tesla, Porsche, Audi e-tron, BMW, Mercedes, and BYD",
      "Heavy-duty XLPE armoured cabling from main DB with conduit dressing",
      "Dedicated Type A/B RCBO earth leakage circuit breaker protection",
      "IP65 waterproof outdoor rotary isolator switch installation",
      "Complete commissioning, app pairing, and load testing",
    ],
    faqs: [
      {
        question: "Do I need DEWA approval to install an EV charger in my villa?",
        answer: "For standard residential villa wallboxes up to 22kW, our certified electricians ensure the load fits within your existing sanctioned DEWA allocation.",
      },
    ],
    metaTitle: "EV Charger Installation Dubai | Tesla & Universal Wallbox",
    metaDesc: "Professional EV charger installation for villas in Dubai. Certified electricians, armored cabling, dedicated RCBO protection.",
  },

  // Handyman & Carpentry
  {
    id: "srv-handyman",
    name: "Professional Handyman Services",
    slug: "handyman",
    categoryId: "cat-handyman",
    categorySlug: "handyman",
    categoryName: "Handyman & Carpentry",
    image: "https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Experienced handyman squad for IKEA / bespoke furniture assembly, TV wall mounting, chandelier hanging, curtain rods, and door locks.",
    fullContent: `Equipped with laser levels, heavy-duty stud finders, and premium anchors, our uniformed handymen handle every home fix with precision, leaving zero mess behind.`,
    basePriceAED: 149,
    priceUnit: "per hour (includes basic fixings)",
    emergencyAvailable: true,
    isPopular: true,
    isActive: true,
    features: [
      "IKEA, Home Centre, and bespoke luxury furniture assembly",
      "Secure TV wall mounting on drywall, concrete, and tiled walls",
      "Chandelier, pendant light, and mirror hanging with laser leveling",
      "Door lock, smart digital lock, and door closer installations",
      "Curtain tracks, roman blinds, and shelving unit fixing",
    ],
    faqs: [
      {
        question: "Do your handymen bring their own tools and fixings?",
        answer: "Yes, our mobile vans arrive with professional power tools, drywall anchors, masonry plugs, laser levels, and step ladders.",
      },
    ],
    metaTitle: "Reliable Handyman Services Dubai | Hourly & Fixed Rates",
    metaDesc: "Best handyman service in Dubai. TV mounting, furniture assembly, curtain hanging, locks, chandeliers. Same-day booking.",
  },
  {
    id: "srv-carpentry",
    name: "Carpentry & Woodwork Repair",
    slug: "carpentry",
    categoryId: "cat-handyman",
    categorySlug: "handyman",
    categoryName: "Handyman & Carpentry",
    image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Custom wooden door repair, kitchen cabinet hinge alignment, bespoke wardrobes, wooden flooring fixes, and pergolas.",
    fullContent: `Expert carpenters for custom cabinetry, swollen door adjustments due to humidity, soft-close hinge upgrades, and wooden deck restoration.`,
    basePriceAED: 180,
    priceUnit: "per service visit",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Wooden door trimming, latch realignment, and acoustic weatherstripping",
      "Kitchen cabinet drawer slides and Blum soft-close hinge upgrades",
      "Parquet and laminate wooden flooring repair and plank replacement",
      "Custom wardrobe shelving and vanity unit modifications",
      "Outdoor wooden deck and pergola sanding & weatherproofing",
    ],
    faqs: [
      {
        question: "Can you fix doors that stick or don't close properly?",
        answer: "Yes, humidity frequently causes wooden doors in UAE villas to expand. We trim and realign the hinges to ensure smooth closing.",
      },
    ],
    metaTitle: "Carpentry & Woodwork Services Dubai | Door & Cabinet Repair",
    metaDesc: "Professional carpenters in Dubai. Door trimming, kitchen cabinet repair, wardrobe fixing, wooden flooring. Call today.",
  },

  // Painting & Waterproofing
  {
    id: "srv-villa-painting",
    name: "Villa & Apartment Painting",
    slug: "painting",
    categoryId: "cat-painting",
    categorySlug: "painting-waterproofing",
    categoryName: "Painting & Waterproofing",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Premium Jotun Fenomastic interior paint, UV-resistant exterior elastomeric villa coatings, and Italian Marmorino stucco.",
    fullContent: `Protect and elevate your property with elite painting craftsmanship. We utilize Jotun Jotashield Extreme heat-reflective exterior coatings engineered to reduce indoor heat gain by up to 5°C under the Arabian sun, alongside flawless dust-free interior finishes with zero VOC emissions.`,
    basePriceAED: 950,
    priceUnit: "per room / zone",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Jotun Jotashield Extreme UV-reflective exterior coating with 10-year warranty",
      "Dustless Festool surface sanding with 100% floor and furniture masking protection",
      "Luxury Italian decorative finishes (Marmorino, Travertino, Velvet Stucco)",
      "Moisture-cured crack bridging primers for coastal villa facades",
      "Free 3D digital colour visualization & designer moodboard consultation",
    ],
    faqs: [
      {
        question: "How long does a full 4-bedroom villa interior painting take?",
        answer: "A full 4-bedroom luxury villa interior typically requires 3 to 4 working days with our dedicated multi-craftsman squad, including complete masking and post-clean.",
      },
    ],
    metaTitle: "Villa & Apartment Painting Services Dubai | Jotun Approved",
    metaDesc: "Flawless interior & exterior villa painting in Dubai. Jotun Fenomastic, Jotashield, complete furniture masking. Free quote.",
  },
  {
    id: "srv-waterproofing",
    name: "Roof & Bathroom Waterproofing",
    slug: "waterproofing",
    categoryId: "cat-painting",
    categorySlug: "painting-waterproofing",
    categoryName: "Painting & Waterproofing",
    image: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Polyurethane liquid membrane, combo roof waterproofing system, bathroom sub-floor tanking, and balcony leak sealing.",
    fullContent: `Defend against catastrophic water ingress. We install Dubai Municipality compliant combo waterproofing systems on villa roofs, elastomeric polyurethane membranes, and torch-applied bitumen membranes with guaranteed leak-free warranties.`,
    basePriceAED: 45,
    priceUnit: "per square meter",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Approved Combo Roof Waterproofing System (PIR insulation + PU membrane)",
      "Bathroom and wet area sub-tile liquid polymer tanking",
      "Polyurethane injection grouting for active concrete crack leaks",
      "Balcony and planter box waterproofing with drainage geofabric",
      "10-Year transferable warranty certificate provided",
    ],
    faqs: [
      {
        question: "How do you fix balcony floor leaks without removing all tiles?",
        answer: "Depending on the sub-base, we utilize deep-penetrating hydrophobic clear sealants or remove the perimeter tile line to inject elastomeric membranes.",
      },
    ],
    metaTitle: "Roof & Bathroom Waterproofing Contractors Dubai UAE",
    metaDesc: "Certified waterproofing contractors in Dubai. Combo roof systems, PU liquid membrane, bathroom tanking. 10-year warranty.",
  },

  // Renovation & Fit-Out
  {
    id: "srv-marble-polishing",
    name: "Italian Marble Crystallization & Polishing",
    slug: "marble-polishing",
    categoryId: "cat-renovation",
    categorySlug: "renovation-fitout",
    categoryName: "Renovation & Fit-Out",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Diamond disc planetary grinding, Italian fluorosilicate crystallization, epoxy grout restoration, and nano stain proofing.",
    fullContent: `Restore the mirror gloss of your Carrara, Crema Marfil, Statuario, or Travertine marble floors. Our stone care artisans remove scratches, etch marks, and dullness using Klindex heavy diamond grinders followed by nano-crystallization sealants for long-lasting brilliance.`,
    basePriceAED: 35,
    priceUnit: "per square meter",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Multi-step diamond abrasive grit honing (200 to 3000 grit)",
      "Italian fluorosilicate crystallization for high-gloss mirror finish",
      "Color-matched Italian epoxy mastic joint regrouting and leveling",
      "Hydrophobic and oleophobic deep penetrating nano-sealant application",
      "Zero harsh acids — safe for delicate onyx, limestone, and marble",
    ],
    faqs: [
      {
        question: "Will diamond grinding make my house dusty?",
        answer: "No, our Italian Klindex planetary machines operate using continuous wet-slurry grinding which produces zero airborne dust.",
      },
    ],
    metaTitle: "Italian Marble Polishing & Crystallization Dubai UAE",
    metaDesc: "Diamond abrasive grinding, Italian crystallization, and nano-sealing for luxury marble and travertine floors in Dubai & Abu Dhabi.",
  },
  {
    id: "srv-tiling",
    name: "Tiling & Grouting Services",
    slug: "tiling",
    categoryId: "cat-renovation",
    categorySlug: "renovation-fitout",
    categoryName: "Renovation & Fit-Out",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Large-format porcelain slab installation, ceramic tile replacement, hollow tile re-bonding, and waterproof epoxy grouting.",
    fullContent: `Precision tile fixing for villa floors, bathrooms, swimming pools, and outdoor patios. We handle large-format 120x240cm porcelain slabs using laser leveling and heavy-duty polymer-modified adhesives.`,
    basePriceAED: 65,
    priceUnit: "per square meter (labour)",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Large-format porcelain, ceramic, terrazzo, and mosaic installation",
      "Anti-stain waterproof epoxy grouting (Mapei / Weber)",
      "Hollow and loose tile re-bonding without cracking surrounding tiles",
      "Laser leveling system for 100% lippage-free flush surfaces",
      "Exterior non-slip patio and swimming pool coping tiling",
    ],
    faqs: [
      {
        question: "Can you fix cracked or hollow tiles without redoing the whole floor?",
        answer: "Yes, we can carefully remove individual damaged tiles or inject high-strength epoxy resin beneath hollow tiles to restore solid bonding.",
      },
    ],
    metaTitle: "Tiling & Grouting Contractors Dubai | Floor & Wall Tiles",
    metaDesc: "Expert tile fixing in Dubai. Large format porcelain, ceramic, epoxy grouting, bathroom & patio tiling. Free site estimate.",
  },
  {
    id: "srv-false-ceiling",
    name: "False Ceiling & Drywall Partitions",
    slug: "false-ceiling",
    categoryId: "cat-renovation",
    categorySlug: "renovation-fitout",
    categoryName: "Renovation & Fit-Out",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Gypsum board false ceiling design, cove LED profiles, acoustic drywall office partitions, and moisture-resistant bathroom ceilings.",
    fullContent: `Modernize your interiors with contemporary shadow-gap false ceilings, magnetic track lighting channels, and acoustic drywall room partitions using Knauf and Gyproc certified systems.`,
    basePriceAED: 75,
    priceUnit: "per square meter",
    emergencyAvailable: false,
    isPopular: false,
    isActive: true,
    features: [
      "Knauf moisture-resistant (MR) and fire-rated gypsum board systems",
      "Modern shadow gap profiles, curtain pelmets, and indirect LED coves",
      "Acoustic insulated drywall partitions with rockwool soundproofing",
      "Access panel integration for easy HVAC and electrical maintenance",
      "Smooth level 5 joint taping, skimming, and paint-ready finish",
    ],
    faqs: [
      {
        question: "How long does it take to install a false ceiling in an apartment?",
        answer: "A standard living room or bedroom false ceiling typically takes 2 to 3 days from framing to paint-ready finishing.",
      },
    ],
    metaTitle: "False Ceiling & Gypsum Drywall Partitions Dubai",
    metaDesc: "Custom gypsum false ceiling installation, shadow gap profiles, acoustic drywall partitions in Dubai. Commercial & residential.",
  },
  {
    id: "srv-kitchen-renovation",
    name: "Kitchen Renovation & Remodeling",
    slug: "kitchen-renovation",
    categoryId: "cat-renovation",
    categorySlug: "renovation-fitout",
    categoryName: "Renovation & Fit-Out",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Turnkey kitchen remodeling, custom German/Italian cabinetry, quartz & porcelain countertops, and appliance integration.",
    fullContent: `Transform your kitchen into a luxurious culinary space. We manage the entire lifecycle from 3D layout design and demolition to quartz waterfall countertops, plumbing relocation, and smart ambient lighting.`,
    basePriceAED: 12500,
    priceUnit: "per turnkey project starting from",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Custom waterproof MDF / plywood modular cabinets with soft-close hardware",
      "Calacatta quartz, granite, and sintered stone waterfall countertops",
      "Integrated sink, drainer, dishwasher, and hood ducting relocation",
      "Full DEWA compliant electrical rewiring and under-cabinet LED tracks",
      "Turnkey project management with dedicated site supervisor",
    ],
    faqs: [
      {
        question: "Do you handle building management (NOC) and permits?",
        answer: "Yes, we handle all necessary developer and Dubai Municipality NOC approvals and work permits.",
      },
    ],
    metaTitle: "Luxury Kitchen Renovation & Remodeling Dubai",
    metaDesc: "Turnkey kitchen renovation in Dubai. Custom modern cabinets, quartz countertops, plumbing & electrical. Free 3D design.",
  },
  {
    id: "srv-bathroom-renovation",
    name: "Bathroom Renovation & Upgrades",
    slug: "bathroom-renovation",
    categoryId: "cat-renovation",
    categorySlug: "renovation-fitout",
    categoryName: "Renovation & Fit-Out",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Complete bathroom makeover, walk-in frameless glass showers, concealed cisterns (Geberit), Grohe/Kohler fixtures, and tiling.",
    fullContent: `Upgrade old bathrooms into spa-like retreats. We handle waterproofing tanking, concealed Geberit wall-hung toilets, custom vanity units, frameless shower enclosures, and designer sanitary fittings.`,
    basePriceAED: 8500,
    priceUnit: "per bathroom starting from",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "100% Waterproof tanking membrane with 10-year leak guarantee",
      "Concealed cistern installation (Geberit / Grohe) and wall-hung pans",
      "Custom 10mm tempered glass frameless walk-in shower partitions",
      "Large format wall and non-slip floor tile installation",
      "LED backlit anti-fog mirrors and luxury rain shower systems",
    ],
    faqs: [
      {
        question: "How long does a full bathroom makeover take?",
        answer: "A standard complete bathroom renovation takes 7 to 10 working days from demolition to final silicone sealing.",
      },
    ],
    metaTitle: "Complete Bathroom Renovation & Remodeling Dubai",
    metaDesc: "Luxury bathroom renovations in Dubai. Geberit concealed cisterns, walk-in glass showers, Grohe fittings, waterproof tiling.",
  },
  {
    id: "srv-villa-renovation",
    name: "Full Villa & Apartment Renovation",
    slug: "villa-renovation",
    categoryId: "cat-renovation",
    categorySlug: "renovation-fitout",
    categoryName: "Renovation & Fit-Out",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Complete turnkey residential and commercial property overhaul: MEP upgrades, flooring, smart automation, and luxury fit-out.",
    fullContent: `Complete interior and exterior property transformation across Palm Jumeirah, Emirates Hills, and Arabian Ranches. From wall demolition and layout restructuring to high-end joinery and smart home automation.`,
    basePriceAED: 35000,
    priceUnit: "per project starting from",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Full architectural 3D rendering and interior design concept",
      "Complete MEP overhaul (HVAC, plumbing, electrical, and drainage)",
      "Luxury Italian marble flooring and bespoke joinery fit-out",
      "Building permit, authority approval, and developer NOC processing",
      "Fixed price contract with milestone-based payments and penalty SLA",
    ],
    faqs: [
      {
        question: "Can you provide a fixed price guarantee on renovation?",
        answer: "Yes, following a detailed site survey and scope finalization, we provide a binding fixed-price contract with zero surprise costs.",
      },
    ],
    metaTitle: "Turnkey Villa & Apartment Renovation Dubai | Fit-Out Contractor",
    metaDesc: "High-end villa and penthouse renovations in Dubai. Complete MEP, marble, joinery, and authority approvals. Free site survey.",
  },

  // Cleaning & Pool Maintenance
  {
    id: "srv-deep-cleaning",
    name: "Deep Cleaning & Sanitization",
    slug: "deep-cleaning",
    categoryId: "cat-cleaning",
    categorySlug: "cleaning-maintenance",
    categoryName: "Cleaning & Pool Maintenance",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Intensive deep steam cleaning, post-renovation cleanup, kitchen degreasing, grout scrubbing, and villa window washing.",
    fullContent: `Ensure your property is 100% spotless and sanitized. Our deep cleaning squad uses industrial floor single-disc scrubbers, 180°C steam extractors, and hospital-grade disinfectants to eliminate built-up grime, paint residue, and bacteria.`,
    basePriceAED: 499,
    priceUnit: "per 2-Bedroom flat / villa starting",
    emergencyAvailable: false,
    isPopular: true,
    isActive: true,
    features: [
      "Heavy-duty single-disc rotary machine floor scrubbing",
      "High-pressure 180°C steam sanitization of bathrooms & kitchens",
      "Full kitchen degreasing (oven, hood, cabinets inside/out)",
      "Window glass and track cleaning with streak-free squeegees",
      "Balcony and patio pressure washing included",
    ],
    faqs: [
      {
        question: "What is the difference between regular cleaning and deep cleaning?",
        answer: "Deep cleaning uses industrial machinery and steam to reach behind appliances, inside grout lines, window tracks, and sanitizes every surface.",
      },
    ],
    metaTitle: "Professional Deep Cleaning Services Dubai | Move-In Cleaning",
    metaDesc: "Top-rated deep cleaning for villas and apartments in Dubai. Steam sanitization, floor scrubbing, post-renovation cleaning.",
  },
  {
    id: "srv-swimming-pool",
    name: "Swimming Pool Maintenance & Chiller Repair",
    slug: "swimming-pool-maintenance",
    categoryId: "cat-cleaning",
    categorySlug: "cleaning-maintenance",
    categoryName: "Cleaning & Pool Maintenance",
    image: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Bi-weekly pool water chemical balancing, robotic vacuuming, sand filter cleaning, and pool chiller / heat pump repair.",
    fullContent: `Keep your private villa pool crystal clear and temperature-regulated year-round. We provide certified pool technicians who manage pH/chlorine chemistry, clean sand filters, service heat pumps/chillers, and perform leak testing on underwater fittings.`,
    basePriceAED: 499,
    priceUnit: "per month (bi-weekly visits)",
    emergencyAvailable: true,
    isPopular: false,
    isActive: true,
    features: [
      "Twice-weekly water testing, vacuuming, skimming, and wall scrubbing",
      "Digital photometer testing for free chlorine, cyanuric acid, and alkalinity",
      "Titanium heat/cool inverter pool chiller compressor servicing",
      "Sand filter backwashing, glass media replacement, and pump seal overhauls",
      "Underwater LED light fixture replacements and IP68 junction sealing",
    ],
    faqs: [
      {
        question: "Can you fix a pool chiller that is not cooling in summer?",
        answer: "Yes, our HVAC pool technicians service all major pool chiller brands (Hayward, Oasis, Pentair) including refrigerant leak detection and compressor repairs.",
      },
    ],
    metaTitle: "Swimming Pool Cleaning & Chiller Maintenance Dubai",
    metaDesc: "Twice-weekly swimming pool maintenance, water chemistry, pool pump and chiller repair across Dubai villas. Monthly plans from AED 499.",
  },
];

export const LOCATIONS: LocationData[] = [
  // Dubai Premium Hubs
  {
    id: "loc-dubai-marina",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Dubai Marina",
    neighborhoodSlug: "dubai-marina",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 20,
    techniciansOnDuty: 8,
    postalCode: "39200",
    latitude: 25.0772,
    longitude: 55.1332,
    metaTitle: "24/7 Technical Services & Emergency Maintenance in Dubai Marina | 20 Min ETA",
    metaDesc: "Top-rated 24/7 AC repair, plumbing, electrical, and AMC maintenance in Dubai Marina towers and penthouses. Rapid 20-minute response.",
  },
  {
    id: "loc-palm-jumeirah",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Palm Jumeirah",
    neighborhoodSlug: "palm-jumeirah",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 18,
    techniciansOnDuty: 7,
    postalCode: "39201",
    latitude: 25.1124,
    longitude: 55.139,
    metaTitle: "Luxury Villa Maintenance & Technical Services in Palm Jumeirah Dubai",
    metaDesc: "Exclusive villa AC duct cleaning, emergency plumbing, marble polishing, and AMC contracts for Palm Jumeirah Fronds and Crescent residences.",
  },
  {
    id: "loc-downtown-dubai",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Downtown Dubai",
    neighborhoodSlug: "downtown-dubai",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 22,
    techniciansOnDuty: 7,
    postalCode: "39202",
    latitude: 25.1972,
    longitude: 55.2744,
    metaTitle: "Premium Property Maintenance in Downtown Dubai & Burj Khalifa District",
    metaDesc: "24/7 residential & commercial technical services in Downtown Dubai, Business Bay, and Opera District. Rapid on-site response.",
  },
  {
    id: "loc-business-bay",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Business Bay",
    neighborhoodSlug: "business-bay",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 24,
    techniciansOnDuty: 6,
    postalCode: "39205",
    latitude: 25.1837,
    longitude: 55.2666,
    metaTitle: "Commercial & Residential Technical Services in Business Bay Dubai",
    metaDesc: "Fast-track corporate fit-out, AC chiller maintenance, electrical audits, and emergency repairs for Business Bay commercial & residential towers.",
  },
  {
    id: "loc-jvc",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Jumeirah Village Circle (JVC)",
    neighborhoodSlug: "jvc",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 22,
    techniciansOnDuty: 8,
    postalCode: "39208",
    latitude: 25.0601,
    longitude: 55.2081,
    metaTitle: "JVC Home Maintenance, AC Repair & Handyman Services Dubai",
    metaDesc: "Fast 24/7 AC repair, plumbing, electrical, and painting in JVC (Jumeirah Village Circle) apartments and townhouses.",
  },
  {
    id: "loc-dubai-hills",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Dubai Hills Estate",
    neighborhoodSlug: "dubai-hills",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 20,
    techniciansOnDuty: 6,
    postalCode: "39206",
    latitude: 25.1118,
    longitude: 55.2494,
    metaTitle: "Dubai Hills Estate Villa Maintenance & Technical Services",
    metaDesc: "Comprehensive home maintenance, AC deep sanitization, villa painting, and pool upkeep in Dubai Hills Estate and Maple.",
  },
  {
    id: "loc-arabian-ranches",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Arabian Ranches",
    neighborhoodSlug: "arabian-ranches",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 25,
    techniciansOnDuty: 5,
    postalCode: "39204",
    latitude: 25.0561,
    longitude: 55.2635,
    metaTitle: "Arabian Ranches Villa AC Repair, Plumbing & Painting Services Dubai",
    metaDesc: "Certified villa technicians serving Arabian Ranches 1, 2 & 3, Mudon, and Damac Hills with prompt HVAC, plumbing, and painting care.",
  },
  {
    id: "loc-emirates-hills",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Emirates Hills",
    neighborhoodSlug: "emirates-hills",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 20,
    techniciansOnDuty: 5,
    postalCode: "39203",
    latitude: 25.0688,
    longitude: 55.1764,
    metaTitle: "Elite Villa Maintenance & AMC Packages in Emirates Hills Dubai",
    metaDesc: "High-end maintenance solutions for luxury mansions in Emirates Hills, The Meadows, and The Lakes. 24/7 dedicated dispatch squad.",
  },
  {
    id: "loc-jumeirah",
    city: "Dubai",
    citySlug: "dubai",
    neighborhood: "Jumeirah",
    neighborhoodSlug: "jumeirah",
    emirate: "Dubai",
    isHighDemand: true,
    avgResponseMins: 20,
    techniciansOnDuty: 6,
    postalCode: "39209",
    latitude: 25.1872,
    longitude: 55.2415,
    metaTitle: "Jumeirah Villa Maintenance, AC Repair & Plumbing Dubai",
    metaDesc: "Trusted maintenance for luxury villas in Jumeirah 1, 2, 3, and Umm Suqeim. DEWA certified master technicians.",
  },

  // Abu Dhabi Hubs
  {
    id: "loc-yas-island",
    city: "Abu Dhabi",
    citySlug: "abu-dhabi",
    neighborhood: "Yas Island",
    neighborhoodSlug: "yas-island",
    emirate: "Abu Dhabi",
    isHighDemand: true,
    avgResponseMins: 28,
    techniciansOnDuty: 5,
    postalCode: "51100",
    latitude: 24.4984,
    longitude: 54.6044,
    metaTitle: "Yas Island Villa Maintenance & Emergency Technical Services Abu Dhabi",
    metaDesc: "24/7 property care, AC repair, plumbing, and luxury maintenance across Yas Acres, Mayan, and West Yas.",
  },
  {
    id: "loc-saadiyat-island",
    city: "Abu Dhabi",
    citySlug: "abu-dhabi",
    neighborhood: "Saadiyat Island",
    neighborhoodSlug: "saadiyat-island",
    emirate: "Abu Dhabi",
    isHighDemand: true,
    avgResponseMins: 28,
    techniciansOnDuty: 4,
    postalCode: "51101",
    latitude: 24.5367,
    longitude: 54.4332,
    metaTitle: "Saadiyat Island Luxury Beachfront Villa Maintenance Abu Dhabi",
    metaDesc: "Ultra-luxury property maintenance, marble crystallization, and HVAC servicing for Saadiyat Beach Villas and Cultural District residences.",
  },
  {
    id: "loc-al-reem-island",
    city: "Abu Dhabi",
    citySlug: "abu-dhabi",
    neighborhood: "Al Reem Island",
    neighborhoodSlug: "al-reem-island",
    emirate: "Abu Dhabi",
    isHighDemand: true,
    avgResponseMins: 25,
    techniciansOnDuty: 6,
    postalCode: "51102",
    latitude: 24.4942,
    longitude: 54.4069,
    metaTitle: "Al Reem Island Apartment Maintenance & AC Servicing Abu Dhabi",
    metaDesc: "Tower apartment AC maintenance, electrical troubleshooting, and emergency plumbing for Marina Square, Gate Towers, and City of Lights.",
  },

  // Sharjah Hubs
  {
    id: "loc-al-zahia",
    city: "Sharjah",
    citySlug: "sharjah",
    neighborhood: "Al Zahia",
    neighborhoodSlug: "al-zahia",
    emirate: "Sharjah",
    isHighDemand: true,
    avgResponseMins: 30,
    techniciansOnDuty: 4,
    postalCode: "61100",
    latitude: 25.3218,
    longitude: 55.4851,
    metaTitle: "Al Zahia Gated Community Villa Maintenance & AC Services Sharjah",
    metaDesc: "Dedicated technical services squad for Al Zahia Uptown and Garden villa owners in Sharjah. 24/7 fast dispatch.",
  },
  {
    id: "loc-aljada",
    city: "Sharjah",
    citySlug: "sharjah",
    neighborhood: "Aljada",
    neighborhoodSlug: "aljada",
    emirate: "Sharjah",
    isHighDemand: false,
    avgResponseMins: 30,
    techniciansOnDuty: 4,
    postalCode: "61101",
    latitude: 25.3197,
    longitude: 55.4744,
    metaTitle: "Aljada Modern Home Maintenance & Technical Services Sharjah",
    metaDesc: "Smart home electrical, AC filter sanitization, plumbing, and turnkey AMC maintenance for Aljada residences.",
  },
];

export const AMC_PACKAGES: AMCPackageData[] = [
  {
    id: "amc-silver",
    name: "Silver Essentials",
    slug: "silver-essentials",
    tier: "SILVER",
    priceAnnualAED: 1850,
    priceMonthlyAED: 169,
    visitsPerYear: 3,
    emergencyCallouts: 6,
    acServiceCount: 3,
    plumbingCheckups: 2,
    electricalAudits: 2,
    freeSparePartsAED: 200,
    targetPropertyType: "Apartments & 1-2 Bedroom Flats",
    features: [
      "3 Planned preventative HVAC maintenance visits per year",
      "6 Emergency callouts with 60-minute daytime SLA",
      "Full AC coil pressure wash, filter disinfection & gas top-up",
      "Plumbing drainage and sanitary fixture pressure checks",
      "Electrical distribution board thermal inspection",
      "200 AED complimentary consumable spare parts credit",
      "20% VIP discount on all specialized fit-out services",
    ],
    isFeatured: false,
  },
  {
    id: "amc-gold",
    name: "Gold Villa Care",
    slug: "gold-villa-care",
    tier: "GOLD",
    priceAnnualAED: 3850,
    priceMonthlyAED: 349,
    visitsPerYear: 4,
    emergencyCallouts: -1, // Unlimited
    acServiceCount: 4,
    plumbingCheckups: 4,
    electricalAudits: 4,
    freeSparePartsAED: 600,
    targetPropertyType: "3-5 Bedroom Townhouses & Luxury Villas",
    features: [
      "4 Comprehensive quarterly preventative visits across all MEP systems",
      "UNLIMITED 24/7 Emergency callouts with 30-minute priority response",
      "Complete AC chemical duct cleaning & antibacterial fogging (1 Zone free)",
      "Annual water tank deep cleaning and lab test certification included",
      "Water booster pump inspection and pressure vessel calibration",
      "Full DEWA compliance safety audit and thermal DB scan",
      "600 AED free spare parts and plumbing consumables per year",
      "Dedicated Senior Property Maintenance Account Manager",
    ],
    isFeatured: true,
  },
  {
    id: "amc-platinum",
    name: "Platinum Royal Prestige",
    slug: "platinum-royal-prestige",
    tier: "PLATINUM",
    priceAnnualAED: 7950,
    priceMonthlyAED: 719,
    visitsPerYear: 6,
    emergencyCallouts: -1, // Unlimited
    acServiceCount: 6,
    plumbingCheckups: 6,
    electricalAudits: 6,
    freeSparePartsAED: 1500,
    targetPropertyType: "Ultra-Luxury Mansions, Penthouses & Commercial Estates",
    features: [
      "6 Bi-monthly executive preventative maintenance audits",
      "VIP Zero-Wait 24/7 Rapid Dispatch (Sub-20 minute arrival guarantee)",
      "Twice-weekly swimming pool maintenance and pool chiller diagnostics",
      "Complete annual villa water tank cleaning + 2x AC duct sterilizations",
      "Annual Italian marble floor crystallization & nano-sealing (Up to 100 sqm)",
      "1,500 AED complimentary genuine OEM spare parts replacement pool",
      "Direct 24/7 WhatsApp VIP concierge line to Operations Director",
      "Free thermal imaging building envelope insulation leak survey",
    ],
    isFeatured: false,
  },
];

export const PORTFOLIO_ITEMS: PortfolioItemData[] = [
  {
    id: "port-1",
    title: "AC Coil Chemical Decontamination & Cooling Airflow Boost",
    slug: "ac-coil-chemical-decontamination",
    categorySlug: "ac-services",
    locationName: "Palm Jumeirah Signature Villa",
    beforeImage: "/images/ac_coil_before.jpg",
    afterImage: "/images/ac_coil_after.jpg",
    completionTime: "2 Hours Turnaround",
    clientType: "6-Bedroom Beachfront Villa",
    description: "Eliminated severe humidity-induced bio-film and clogged evaporator coils. Restored cooling airflow velocity by 40% and balanced indoor temperature across all suites.",
    resultsAchieved: [
      "Sub-20°C icy cooling restored during 48°C peak desert summer",
      "Airborne particulate matter (PM2.5) reduced by 94%",
      "Client achieved 22% monthly reduction in DEWA electricity consumption",
    ],
  },
  {
    id: "port-2",
    title: "Distribution Board (DB) Rewiring & DEWA Safety Overhaul",
    slug: "db-box-rewiring-dewa-safety",
    categorySlug: "electrical",
    locationName: "Downtown Dubai Penthouse",
    beforeImage: "/images/db_box_before.jpg",
    afterImage: "/images/db_box_after.jpg",
    completionTime: "4 Hours Execution",
    clientType: "Duplex Luxury Penthouse",
    description: "Complete electrical panel modernization, DEWA load balancing, high-surge protector installation, and organized color-coded breaker layout.",
    resultsAchieved: [
      "Eliminated recurring nuisance RCCB tripping under heavy HVAC load",
      "Full DEWA safety certification and thermal inspection signoff",
      "Surge protection installed for sensitive smart appliances & audio servers",
    ],
  },
  {
    id: "port-3",
    title: "Luxury Interior Wall Restoration & Fenomastic Velvet Painting",
    slug: "villa-interior-wall-painting",
    categorySlug: "painting-waterproofing",
    locationName: "Arabian Ranches Luxury Villa",
    beforeImage: "/images/villa_paint_before.jpg",
    afterImage: "/images/villa_paint_after.jpg",
    completionTime: "2 Days Turnaround",
    clientType: "Standalone 5-Bed Family Villa",
    description: "Surface plaster restoration, hairline crack bridging, and Jotun Fenomastic zero-odor luxury paint application with laser-guided edge lines.",
    resultsAchieved: [
      "100% spotless, streak-free matte velvet finish",
      "Zero lingering chemical odors with ultra-low VOC formulation",
      "Complete furniture masking and spotless post-job cleanup",
    ],
  },
  {
    id: "port-4",
    title: "Central Water Heater Replacement & Pressure Relief Valve",
    slug: "central-water-heater-replacement",
    categorySlug: "plumbing",
    locationName: "Dubai Hills Estate Villa",
    beforeImage: "/images/water_heater_before.jpg",
    afterImage: "/images/water_heater_after.jpg",
    completionTime: "90 Minutes Arrival & Fix",
    clientType: "Contemporary Townhouse",
    description: "Emergency replacement of corroded tank unit with high-efficiency Italian Ariston system, pressure relief valves, and reinforced braided flex hoses.",
    resultsAchieved: [
      "Zero ceiling water staining or secondary structural damage",
      "Safety pressure valves calibrated to official municipality specs",
      "5-Year manufacturer warranty card issued on-site",
    ],
  },
];

export const TESTIMONIALS: TestimonialData[] = [
  {
    id: "test-1",
    authorName: "Tariq Al-Maktoum",
    authorRole: "Villa Owner",
    neighborhood: "Palm Jumeirah",
    city: "Dubai",
    rating: 5,
    reviewText: "When our central chiller failed on a Friday afternoon in August with 46°C heat, Al-Safwa's emergency team arrived in 22 minutes. They diagnosed a burnt capacitor, replaced it with an OEM part, and had ice-cold air flowing before our guests arrived. Flawless service.",
    verifiedPurchase: true,
    serviceName: "AC Repair & Emergency Maintenance",
    date: "August 2026",
  },
  {
    id: "test-2",
    authorName: "Charlotte & Alexander Wright",
    authorRole: "Homeowners",
    neighborhood: "Emirates Hills",
    city: "Dubai",
    rating: 5,
    reviewText: "We enrolled in the Gold Villa Care AMC two years ago. Their quarterly maintenance is unmatched. Zero unexpected breakdowns, our DEWA bills dropped by 18%, and the technicians are always courteous, uniformed, and wear protective shoe covers.",
    verifiedPurchase: true,
    serviceName: "Gold Villa Care AMC",
    date: "July 2026",
  },
  {
    id: "test-3",
    authorName: "Eng. Rashid Al-Kaabi",
    authorRole: "Property Asset Manager",
    neighborhood: "Saadiyat Island",
    city: "Abu Dhabi",
    rating: 5,
    reviewText: "Managing luxury coastal properties in Abu Dhabi requires contractors who understand marine salt corrosion and high humidity. Al-Safwa has been our exclusive maintenance partner for 8 villas. Their thermal leak detection saved us hundreds of thousands in potential structural damage.",
    verifiedPurchase: true,
    serviceName: "Emergency Plumbing & Thermal Leak Detection",
    date: "September 2026",
  },
  {
    id: "test-4",
    authorName: "Kareem El-Sayed",
    authorRole: "Apartment Resident",
    neighborhood: "Dubai Marina",
    city: "Dubai",
    rating: 5,
    reviewText: "Booked an emergency plumber through WhatsApp at 11:30 PM for a kitchen riser pipe leak. The technician arrived in 18 minutes with all required tools and replacement valves. Extremely professional and clean work.",
    verifiedPurchase: true,
    serviceName: "Emergency Plumbing Services",
    date: "September 2026",
  },
];

export const BLOG_POSTS: BlogPostData[] = [
  {
    id: "blog-1",
    title: "The Ultimate Guide to Maintaining Your AC in UAE Summer (45°C+ Survival)",
    slug: "uae-ac-summer-maintenance-guide",
    excerpt: "Learn how to keep your air conditioning icy cool, prevent coil freezing, and reduce high summer DEWA electricity bills with practical expert tips.",
    content: `In the UAE, summer temperatures frequently exceed 45°C with 80%+ coastal humidity. Maintaining peak AC performance requires clean condenser coils, regular filter washings every 3 weeks, and ensuring refrigerant pressures remain calibrated. Discover our master technicians' top recommendations to maximize HVAC longevity.`,
    coverImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    author: "Eng. Farhan Siddiqui (Lead HVAC Specialist)",
    category: "AC & HVAC Care",
    readTime: "5 min read",
    publishedDate: "September 12, 2026",
    metaTitle: "UAE AC Summer Maintenance Guide | Al-Safwa Engineering",
    metaDesc: "Essential tips to protect your AC in Dubai summer heat, prevent breakdowns, and lower DEWA electricity bills.",
  },
  {
    id: "blog-2",
    title: "Why Thermal Leak Detection is Essential for UAE Luxury Villas",
    slug: "why-thermal-leak-detection-matters",
    excerpt: "Hidden water leaks can destroy marble flooring and foundation integrity. Discover how non-destructive FLIR thermal imaging saves thousands in repairs.",
    content: `Water leaks concealed beneath concrete slabs or behind luxury Italian marble walls can go undetected for months until damp patches appear or DEWA water bills spike mysteriously. Thermal imaging cameras detect minute temperature variations caused by moisture without breaking a single tile.`,
    coverImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    author: "Marco Rossi (Master Plumber & Leak Specialist)",
    category: "Plumbing & Protection",
    readTime: "4 min read",
    publishedDate: "August 28, 2026",
    metaTitle: "Thermal Leak Detection for UAE Villas | Al-Safwa Technical",
    metaDesc: "Discover how non-destructive FLIR thermal leak detection saves money and protects property foundations in UAE.",
  },
  {
    id: "blog-3",
    title: "Annual Maintenance Contracts (AMC) vs On-Demand Callouts: Which Saves More?",
    slug: "amc-vs-on-demand-cost-comparison",
    excerpt: "A financial and reliability breakdown of investing in an annual property maintenance contract for Dubai villas vs paying per individual breakdown.",
    content: `Comparing the cost of 4 preventative AC services, emergency plumbing callouts, and water tank cleaning with an all-inclusive Gold AMC package proves that property owners save up to 42% annually while gaining guaranteed sub-30 minute emergency SLAs.`,
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    author: "Zaid Al-Mansoor (Operations Director)",
    category: "Property Management",
    readTime: "6 min read",
    publishedDate: "August 15, 2026",
    metaTitle: "AMC vs On-Demand Maintenance Dubai Cost Comparison",
    metaDesc: "Calculate the real financial benefits of an Annual Maintenance Contract (AMC) for Dubai villas and apartments.",
  },
];

export function getAllLocationServiceCombinations() {
  const combos: { serviceSlug: string; citySlug: string; locationSlug: string }[] = [];
  for (const service of SERVICES) {
    for (const loc of LOCATIONS) {
      combos.push({
        serviceSlug: service.slug,
        citySlug: loc.citySlug,
        locationSlug: loc.neighborhoodSlug,
      });
    }
  }
  return combos;
}

export function getAllCategoryServiceCombinations() {
  const combos: { category: string; serviceSlug: string }[] = [];
  for (const service of SERVICES) {
    if (service.categorySlug) {
      combos.push({
        category: service.categorySlug,
        serviceSlug: service.slug,
      });
    }
  }
  return combos;
}
